apiVersion: v1
kind: Service
metadata:
    name: "hitech4-d489"
    labels:
        app: "hitech4-d489"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "hitech4-d489"